"""One entry point, many pointers.

Every agent runtime looks for its own instruction file. The kit keeps ONE — AGENTS.md — and
generates a pointer file for every runtime it knows, from one template, so that whichever
runtime opens the repository lands on the same instructions, and so that a request to set the
kit up always starts with the onboarding interview. The same generator writes the pointers for
an adopter's repository, with the kit vendored at .pact/ or copied out.

Adding a runtime is one entry in POINTERS. Never edit a generated file by hand: `make entry`
refuses drift; `python3 automation/scripts/entry_points.py` rewrites them.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

ENTRY_POINT = "AGENTS.md"
INTERVIEW = "docs/onboarding/interview.md"
GENERATOR = "automation/scripts/entry_points.py"


@dataclass(frozen=True)
class Pointer:
    runtime: str
    path: str            # relative to the folder the runtime opens
    style: str = "md"    # md · cursor · windsurf · continue · kiro · augment · aider


POINTERS: tuple[Pointer, ...] = (
    Pointer("Claude Code", "CLAUDE.md"),
    Pointer("Claude Code", ".claude/rules/pact.md"),
    Pointer("Gemini CLI", "GEMINI.md"),
    Pointer("Qwen Code", "QWEN.md"),
    Pointer("Warp", "WARP.md"),
    Pointer("Aider", "CONVENTIONS.md"),
    Pointer("Aider", ".aider.conf.yml", "aider"),
    Pointer("Cursor", ".cursor/rules/pact.mdc", "cursor"),
    Pointer("GitHub Copilot", ".github/copilot-instructions.md"),
    Pointer("Windsurf", ".windsurf/rules/pact.md", "windsurf"),
    Pointer("Cline", ".clinerules/pact.md"),
    Pointer("Roo Code", ".roo/rules/pact.md"),
    Pointer("Kilo Code", ".kilocode/rules/pact.md"),
    Pointer("Continue", ".continue/rules/pact.md", "continue"),
    Pointer("JetBrains Junie", ".junie/guidelines.md"),
    Pointer("Kiro", ".kiro/steering/pact.md", "kiro"),
    Pointer("Amazon Q Developer", ".amazonq/rules/pact.md"),
    Pointer("Trae", ".trae/rules/project_rules.md"),
    Pointer("Augment", ".augment/rules/pact.md", "augment"),
    Pointer("Hermes Agent", ".hermes.md"),
    Pointer("Hermes Agent", ".hermes/rules/pact.md"),
    Pointer("Grok", ".grok/rules/pact.md"),
    Pointer("Grok Bot", ".grokbot/rules/pact.md"),
    Pointer("OpenClaw", ".openclaw/rules/pact.md"),
    Pointer("OpenAI Codex", ".codex/rules/pact.md"),
)

# Runtimes that read AGENTS.md on their own. Documentary: they still get a
# folder pointer when that runtime also looks under a dotted directory.
NATIVE_READERS: tuple[str, ...] = (
    "OpenAI Codex", "Cursor", "GitHub Copilot coding agent", "Google Jules", "Amp", "OpenCode",
    "Factory", "Zed", "Devin", "Hermes Agent", "Grok", "OpenClaw",
)

_FRONTMATTER = {
    "cursor": "---\ndescription: PACT — Agentic Delivery Kit. Read AGENTS.md first.\nalwaysApply: true\n---\n\n",
    "windsurf": "---\ntrigger: always_on\n---\n\n",
    "continue": "---\nname: PACT\nalwaysApply: true\n---\n\n",
    "kiro": "---\ninclusion: always\n---\n\n",
    "augment": "---\ntype: always\n---\n\n",
}


def kit_prefix(kit: str | None) -> str:
    """'' when the kit is the repository itself (or copied out); '.pact/' when vendored."""
    kit = (kit or "").strip().rstrip("/").rstrip("\\")
    return "" if kit in ("", ".") else kit + "/"


def render(pointer: Pointer, prefix: str = "") -> str:
    if pointer.style == "aider":
        return (
            f"# Aider reads CONVENTIONS.md, which points to {ENTRY_POINT}. Generated by {prefix}{GENERATOR}.\n"
            "read:\n  - CONVENTIONS.md\n"
        )
    depth = len(Path(pointer.path).parent.parts)
    up = "../" * depth
    # Vendored kit: before the setup exists there is no AGENTS.md at the adopter's root — the
    # pointer sends the runtime to the kit's own entry point, which interviews the person into one.
    fallback = (
        f"If there is none yet, read `{prefix}{ENTRY_POINT}` — the kit's entry point — and it will interview you into one.\n\n"
        if prefix else ""
    )
    links = f"[{ENTRY_POINT}]({up}{ENTRY_POINT})" + (f" · [{prefix}{ENTRY_POINT}]({up}{prefix}{ENTRY_POINT})" if prefix else "")
    body = (
        f"# {pointer.runtime} — entry point\n\n"
        f"Read `{ENTRY_POINT}` at the root of this repository and follow it. It is the single instruction file\n"
        f"for every agent runtime; nothing in this file overrides it.\n\n"
        f"{fallback}"
        f"A request to set this up starts with the interview in `{prefix}{INTERVIEW}`: one block of\n"
        f"questions per turn, wait for the answers, and write no file before the person confirms.\n\n"
        f"{links}\n"
    )
    return _FRONTMATTER.get(pointer.style, "") + body


def expected(root: Path, prefix: str = "") -> dict[Path, str]:
    return {root / p.path: render(p, prefix) for p in POINTERS}


def drift(root: Path, prefix: str = "") -> list[tuple[Path, str]]:
    """(path, problem) for every pointer that is missing or differs from a fresh render."""
    out: list[tuple[Path, str]] = []
    for path, text in expected(root, prefix).items():
        if not path.is_file():
            out.append((path, "missing"))
        elif path.read_text(encoding="utf-8") != text:
            out.append((path, "differs from the generator"))
    return out


def write_all(root: Path, prefix: str = "") -> list[Path]:
    written: list[Path] = []
    for path, text in expected(root, prefix).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        written.append(path)
    return written
