#!/usr/bin/env python3
"""L1 — structure: every internal link and anchor resolves, no orphan document,
every cited RULE id exists, every rule's canon file contains its id, every
runtime pointer file lands on AGENTS.md, and core/ names no tool, vendor,
runtime or profile.

Usage: check_links.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib import entry_points as EP  # noqa: E402
from lib import model as M  # noqa: E402
from lib.report import Report  # noqa: E402

ROOT = M.REPO_ROOT
LINK = re.compile(r"(?<!!)\[[^\]]*\]\(([^)\s]+)\)")
HEADING = re.compile(r"^#{1,6}\s+(.*?)\s*#*\s*$", re.M)
RULE_ID = re.compile(r"\bRULE-[A-Z0-9-]+\b")
SKIP_DIRS = {".git", "__pycache__", ".venv", "venv", "node_modules"}

# Documents that must be reachable from some other document. Root files and
# READMEs are entry points and are exempt.
ORPHAN_ROOTS = ("docs", "core", "templates", "tracks", "agents", "adapters", "profiles", "examples", "automation")

# Every agent runtime lands on AGENTS.md: the pointer files exist and say so.
ENTRY_POINT = "AGENTS.md"
POINTERS = tuple(p.path for p in EP.POINTERS)   # one per runtime, generated by entry_points.py

# The agnosticity test. core/ may not mention any of these — the method must
# not know which tool, vendor, runtime or profile it runs on.
FORBIDDEN_IN_CORE = [
    "azure", "devops", "github", "notion", "slack", "jira", "linear", "trello",
    "claude", "anthropic", "codex", "openai", "gpt", "copilot", "gemini", "cursor",
    "agency", "internal team",
]


def github_anchor(text: str) -> str:
    text = re.sub(r"`([^`]*)`", r"\1", text)
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    text = text.strip().lower()
    text = re.sub(r"[^\w\- ]", "", text)
    return text.replace(" ", "-")


def md_files() -> list[Path]:
    return sorted(
        p for p in ROOT.rglob("*.md")
        if not any(part in SKIP_DIRS for part in p.parts)
    )


def main() -> int:
    report = Report(check="check_links — links, anchors, orphans, rule ids, core agnosticity")
    files = md_files()
    anchors: dict[Path, set[str]] = {}
    for f in files:
        anchors[f] = {github_anchor(h) for h in HEADING.findall(f.read_text(encoding="utf-8"))}

    referenced: set[Path] = set()
    rule_ids = M.rule_ids()

    for f in files:
        text = f.read_text(encoding="utf-8")
        report.scanned += 1
        for lineno, line in enumerate(text.splitlines(), start=1):
            for target in LINK.findall(line):
                if target.startswith(("http://", "https://", "mailto:")):
                    continue
                path_part, _, frag = target.partition("#")
                dest = (f.parent / path_part).resolve() if path_part else f
                if path_part and not dest.exists():
                    report.add(M.rel(f), lineno, "broken-link", f"{target} → {M.rel(dest)} does not exist")
                    continue
                if dest.is_file():
                    referenced.add(dest)
                if frag and dest.suffix == ".md" and dest in anchors and frag not in anchors[dest]:
                    report.add(M.rel(f), lineno, "broken-anchor", f"#{frag} not found in {M.rel(dest)}")
            for rid in RULE_ID.findall(line):
                if rid not in rule_ids:
                    report.add(M.rel(f), lineno, "unknown-rule", f"{rid} is cited but not defined in core/model/rules.yml")

    # every rule's canon file exists and mentions the id
    for r in M.rules():
        canon = ROOT / r["canon"]
        if not canon.is_file():
            report.add("core/model/rules.yml", None, "canon-missing", f"{r['id']}: {r['canon']} does not exist")
        elif r["id"] not in canon.read_text(encoding="utf-8"):
            report.add(r["canon"], None, "canon-mismatch", f"does not mention {r['id']}")

    # orphans: a document nobody links to is a document nobody will read
    for f in files:
        if f.name == "README.md" or f.parent == ROOT:
            continue
        if "_fragments" in f.parts or "fixtures" in f.parts:
            continue  # fragments are reached by fence, fixtures are inputs, not documents
        if f.parts[len(ROOT.parts)] not in ORPHAN_ROOTS:
            continue
        if f not in referenced:
            report.add(M.rel(f), None, "orphan", "no other document links here")

    # entry points: one instruction file, pointed to by every runtime's own name
    if not (ROOT / ENTRY_POINT).is_file():
        report.add(ENTRY_POINT, None, "entry-point", "missing — every runtime must land on it")
    for rel in POINTERS:
        p = ROOT / rel
        if not p.is_file():
            report.add(rel, None, "entry-point", f"missing — must point to {ENTRY_POINT} (run automation/scripts/entry_points.py)")
            continue
        text = p.read_text(encoding="utf-8")
        if ENTRY_POINT not in text:
            report.add(rel, None, "entry-point", f"does not mention {ENTRY_POINT} — pointers point, they do not instruct")
        elif p.suffix in (".md", ".mdc") and "interview" not in text:
            report.add(rel, None, "entry-point", "does not say that a setup starts with the interview — regenerate it")

    # agnosticity of core/
    for f in sorted((ROOT / "core").rglob("*")):
        if not f.is_file() or f.suffix not in (".md", ".yml"):
            continue
        for lineno, line in enumerate(f.read_text(encoding="utf-8").splitlines(), start=1):
            low = line.lower()
            for term in FORBIDDEN_IN_CORE:
                if re.search(rf"\b{re.escape(term)}\b", low):
                    report.add(M.rel(f), lineno, "not-agnostic", f"core/ must not mention {term!r}")

    return report.emit()


if __name__ == "__main__":
    raise SystemExit(main())
